# @package _global_
defaults:
  - override /data: cornell
  - override /model: diag-nsd
  - override /hydra/launcher: slurm


# uncomment the following lines to override the defaults parameters for the trainer
# trainer:
#   max_epochs: 3000 

wandb:
  group: diag-nsd_cornell

hydra:
  sweep:
    dir: ${store_data_path}/multirun/${hydra.job.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweeper:
    params:
      model.num_layers: 2
      model.d: 4
      model.hidden_channels: 16
      model.input_dropout: 0.2
      model.dropout: 0.7
      model.sparse_learner: False
      model.add_lp: True
      model.add_hp: False
      task.optimizer.weight_decay: 0.0006914841722570725
      task.optimizer.sheaf_decay: 0.00031764232712732976
      data.split_idx: range(0, 10)
      seed: 3044291017, 29297748, 115944586, 1193614241, 4217974420



