# @package _global_
defaults:
  - override /data: cora
  - override /model: diag-nsd
  - override /hydra/launcher: slurm


# uncomment the following lines to override the defaults parameters for the trainer
# trainer:
#   max_epochs: 3000 

wandb:
  group: diag-nsd_cora

hydra:
  sweep:
    dir: ${store_data_path}/multirun/${hydra.job.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweeper:
    params:
      model.num_layers: 2, 4
      model.hidden_channels: 16, 32, 64
      model.input_dropout: 0.0
      model.dropout: 0.7
      model.sparse_learner: True, False
      model.add_lp: True
      data.split_idx: range(0, 10)
      seed: 3044291017, 29297748, 115944586, 1193614241, 4217974420



