# @package _global_
defaults:
  - override /data: cornell
  - override /model: snn
  - override /hydra/launcher: slurm


# uncomment the following lines to override the defaults parameters for the trainer
# trainer:
#   max_epochs: 3000 

wandb:
  group: ensd_cornell

hydra:
  sweep:
    dir: ${store_data_path}/multirun/${hydra.job.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweeper:
    params:
      model: snn
      model.num_layers: 2, 4
      model.input_dropout: 0.0
      model.hidden_channels: 16, 32
      model.sheaf_laplacian.type: consistent
      model.sheaf_laplacian.init: random
      model.sheaf_laplacian.d: 3, 4
      model.sheaf_laplacian.add_lp: True, False
      model.sheaf_laplacian.add_hp: True, False
      model.sheaf_laplacian.pretraining.eps: 0.1
      data.split_idx: range(0, 10)
      seed: 3044291017



