# @package _global_
defaults:
  - override /data: cornell
  - override /model: snn
  - override /hydra/launcher: slurm


# uncomment the following lines to override the defaults parameters for the trainer
# trainer:
#   max_epochs: 3000 

wandb:
  group: eps_pretraining_cornell

hydra:
  sweep:
    dir: ${store_data_path}/multirun/${hydra.job.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweeper:
    params:
      model: snn
      model.num_layers: 2
      model.input_dropout: 0.2
      model.dropout: 0.7
      model.hidden_channels: 16
      model.sheaf_laplacian.type: consistent
      model.sheaf_laplacian.init: random
      model.sheaf_laplacian.d: 4
      model.sheaf_laplacian.add_lp: True
      model.sheaf_laplacian.add_hp: False
      data.split_idx: range(1, 10)
      model.sheaf_laplacian.pretraining.eps: -1, 1, 0.5, 0.1, 0.01
      model.sheaf_laplacian.pretraining.num_channels: 32



