# @package _global_
defaults:
  - override /data: wisconsin
  - override /model: energy-acm
  - override /hydra/launcher: slurm


# uncomment the following lines to override the defaults parameters for the trainer
# trainer:
#   max_epochs: 3000 

wandb:
  group: filter-model_wisconsin

hydra:
  sweep:
    dir: ${store_data_path}/multirun/${hydra.job.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweeper:
    params:
      model.num_layers: 2,3,4,6
      model.dropout: 0.5, 0.6, 0.7
      model.hidden_channels: 64
      task.optimizer.lr: 0.01, 0.05, 0.1
      task.optimizer.weight_decay: 0, 5e-6, 1e-5, 5e-5, 1e-4, 5e-4, 1e-3, 5e-3, 1e-2 
      data.split_idx: 0
      seed: 3044291017



