# @package _global_
defaults:
  - override /data: pubmed
  - override /model: snn
  - override /hydra/launcher: slurm


# uncomment the following lines to override the defaults parameters for the trainer
# trainer:
#   max_epochs: 3000 

wandb:
  group: pretraining_pubmed

hydra:
  sweep:
    dir: ${store_data_path}/multirun/${hydra.job.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweeper:
    params:
      model: snn
      model.num_layers: 4
      model.input_dropout: 0.0
      model.hidden_channels: 64
      model.sheaf_laplacian.type: consistent
      model.sheaf_laplacian.init: random
      model.sheaf_laplacian.d: 4
      model.sheaf_laplacian.add_lp: True
      model.sheaf_laplacian.add_hp: True
      model.sheaf_laplacian.pretraining.num_epochs: 0, 10, 25, 50, 75



