# @package _global_
defaults:
  - override /data: cora
  - override /model: snn
  - override /hydra/launcher: slurm


# uncomment the following lines to override the defaults parameters for the trainer
# trainer:
#   max_epochs: 3000 

wandb:
  group: cora_final_snn

hydra:
  sweep:
    dir: ${store_data_path}/multirun/${hydra.job.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweeper:
    params:
      model: snn
      model.num_layers: 4
      model.input_dropout: 0.5
      model.hidden_channels: 64
      model.sheaf_laplacian.type: consistent
      model.sheaf_laplacian.init: random
      model.sheaf_laplacian.d: 4
      model.sheaf_laplacian.add_lp: True
      model.sheaf_laplacian.add_hp: True
      model.sheaf_laplacian.pretraining.num_epochs: 75
      data.split_idx: range(0, 10)
      seed: 3044291017, 29297748, 115944586, 1193614241, 4217974420



