# @package _global_
defaults:
  - override /data: texas
  - override /model: diag-nsd
  - override /hydra/launcher: slurm


# uncomment the following lines to override the defaults parameters for the trainer
# trainer:
#   max_epochs: 3000 

wandb:
  group: spectral-norm_diag-nsd_texas

hydra:
  sweep:
    dir: ${store_data_path}/multirun/${hydra.job.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweeper:
    params:
      data.dim_reduction: True
      model.linear: True
      model.num_layers: 8
      model.left_weights: False, True
      model.right_weights: False, True
      data.split_idx: range(0, 10)
      seed: 3044291017



